name: clmm-rtd

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  - numpy
  - scipy
  - gsl
  - astropy
  - matplotlib
  - ipykernel
  - sphinx
  - sphinx_rtd_theme
  - jupyter_client
  - nbconvert
  - pip:
      - git+https://github.com/tmcclintock/cluster_toolkit.git
