language: python

cache: pip

python:
- "3.6"

install:
  # Update apt-get and install GSL
  - sudo apt-get update
  - sudo apt-get install libgsl0-dev -y

  # Install the dependencies
  - git clone https://github.com/tmcclintock/cluster_toolkit.git ; cd cluster_toolkit ; python setup.py install ; cd -
  - pip install -r requirements.txt

  # Install the package
  - python setup.py install

  # Install dependencies required to test the docs
  - pip install sphinx==2.1.2
  - pip install sphinx_rtd_theme

script:
  # Run the unit tests:
  - py.test --ignore=tests/crypt/ --ignore=cluster_toolkit/tests

  # Run the docs:
  - sphinx-quickstart -a "travis" -p clmm -v 0.0.1 --ext-autodoc -q
  - make -C docs/ html
