language: python

cache: pip

python:
- "3.6" # Minimum supported version
- "3.8-dev" # Why not also test cutting edge?

install:
  # Update apt-get and install GSL
  - sudo apt-get update
  - sudo apt-get install libgsl0-dev -y

  # Install the dependencies
  - git clone https://github.com/tmcclintock/cluster_toolkit.git ; cd cluster_toolkit ; python setup.py install ; cd -
  - pip install -r requirements.txt

  # Install the package
  - python setup.py install

  # Install dependencies required to test the docs
  - pip install sphinx==2.1.2
  - pip install sphinx_rtd_theme

  # Install coveralls for test coverage
  - pip install coveralls pytest-cov

script:
  # Run the unit tests:
  - py.test tests/ --ignore=cluster_toolkit/tests --cov=clmm/

  # Run the docs:
  - sphinx-quickstart -a "travis" -p clmm -v 0.0.1 --ext-autodoc -q
  - make -C docs/ html

after_success:
  - coveralls
