language: python

cache: pip

python:
- "3.6"

install:
  - sudo apt-get update
  - sudo apt-get install libgsl0-dev -y

  # Install the dependencies and the package:
  - git clone https://github.com/matthewkirby/cluster_toolkit.git ; cd cluster_toolkit ; python setup.py install ; cd -
  - pip install -r requirements.txt
  - python setup.py install

  # Finally get set up to build the docs:
  - pip install sphinx==2.1.2
  - pip install sphinx_rtd_theme

script:

  # Run the unit tests:
  - py.test --ignore=tests/crypt/ --ignore=cluster_toolkit/tests

  # Run the docs:
  - sphinx-quickstart -a "travis" -p clmm -v 0.0.1 --ext-autodoc -q
  - make -C docs/ html
