name: Build and Check

on:
  push:
    branches: [ master, add_gha_support ]
  pull_request:
    branches: [ master ]

jobs:
  build-gcc-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install prereq using apt
      run: sudo apt-get install libgsl0-dev swig3.0 libfftw3-dev gobject-introspection python-gobject gfortran libmpfr-dev libhdf5-dev liblapack-dev libnlopt-dev libcfitsio-dev gir1.2-glib-2.0 libgirepository1.0-dev python3-gi python-gi python-numpy python3-matplotlib -y
    - name: Install cluster_toolkit from source
      run: |
        git clone https://github.com/tmcclintock/cluster_toolkit.git
        cd cluster_toolkit
        sudo python setup.py install
    - name: Install CCL from source
      run: |
        git clone https://github.com/LSSTDESC/CCL
        cd CCL
        sudo python setup.py install
    - name: Install NumCosmo from source
      run: |
        wget https://github.com/NumCosmo/NumCosmo/releases/download/v0.15.2/numcosmo-0.15.2.tar.gz
        tar xf numcosmo-0.15.2.tar.gz
        cd numcosmo-0.15.2
        ./configure --prefix=/usr
        make -j4
        sudo make install
    - name: Install prereq using pip
      run: |        
        python3 numcosmo-0.15.2/examples/example_simple.py
        pip install -r requirements.txt
    - name: Install the package
      run: python setup.py install
    - name: Install docs prereq
      run: |
        sudo apt-get install pandoc -y
        pip install ipykernel
        python -m ipykernel install --user --name python3 --display-name python3
        pip install sphinx==2.1.2 sphinx_rtd_theme nbconvert jupyter_client
        pip install coveralls pytest-cov
    - name: Run the unit tests
      run: py.test tests/ --ignore=cluster_toolkit/tests --cov=clmm/
    - name: Run the docs
      run: |
        sphinx-quickstart -a "travis" -p clmm -v 0.0.1 --ext-autodoc -q
        make -C docs/ html

